
const destinations = [
    { id: 1, name: "Paris, France",price: "From $890",image:"images/paris_image.jpg", info: "Welcome to the City of Lights, where timeless elegance meets vibrant culture. Paris, with its iconic landmarks like the Eiffel Tower and Louvre Museum, beckons you to stroll along the Seine, savor croissants in charming cafés, and immerse yourself in art and history. From the chic boutiques of Le Marais to the bohemian charm of Montmartre, Paris is a captivating blend of romance and sophistication. Indulge in the culinary delights of world-renowned bistros, and let the magic of this city steal your heart.", discount: "0%"},
    { id: 2, name: "Italian Riviera", price: "From $890",image:"images/italian_riviera.jpg",info: "Welcome to the Italian Riviera, a sun-kissed stretch along the Ligurian Sea that effortlessly blends coastal glamour with timeless charm. Picture colorful villages cascading down cliffs, with pastel-hued buildings overlooking azure waters. From the iconic charm of Portofino to the rugged beauty of Cinque Terre, the Italian Riviera captivates with its enchanting landscapes" ,discount: "50%"},
    { id: 3, name: "Cinque Terre", price: "From $890",image:"images/cinque_terre.jpg",info: "Discover the breathtaking beauty of Cinque Terre, a cluster of five picturesque villages nestled along the rugged coastline of the Italian Riviera. Each village – Monterosso al Mare, Vernazza, Corniglia, Manarola, and Riomaggiore – is a kaleidoscope of vibrant colors, perched on cliffs that overlook the sparkling Ligurian Sea." ,discount: "50%"},
    { id: 4, name: "Greece", price: "From $890",image:"images/greece.jpg",info: "Welcome to the captivating beauty of Greece, a country where ancient history and modern vibrancy coalesce against a backdrop of stunning landscapes. Explore the Acropolis in Athens, where the Parthenon stands as a testament to ancient civilization, or wander through the charming alleys of Santorini with its iconic blue-domed churches." ,discount: "50%"},
    {id: 5, name: "Costa Rica", price: "From $1000", image:"images/Costa Rica.jpg", info:"Escape to the tropical paradise of Costa Rica, where lush rainforests meet pristine beaches and adventure awaits at every turn. Discover the biodiversity of Manuel Antonio National Park, where monkeys swing through the trees, or embark on a thrilling zip-lining journey above the canopy. Dive into the turquoise waters of the Pacific or Caribbean, surf along the Pacific Coast, and relax in natural hot springs near the Arenal Volcano. Costa Rica, with its pura vida spirit, promises a vibrant tapestry of wildlife, stunning landscapes, and eco-friendly adventures, making it a haven for nature lovers and thrill-seekers alike.", discount: "30%"},
    {id: 6, name: "Bora Bora", price: "From $1250", image:"images/Bora Bora.jpg", info:"Step into the epitome of tropical luxury at Bora Bora, a mesmerizing island in the South Pacific that boasts crystal-clear turquoise waters, lush greenery, and overwater bungalows that redefine paradise. This idyllic destination, surrounded by a coral reef, is a haven for those seeking ultimate relaxation and romance.", discount: "50%"},
    {id: 7, name: "Amserdam", price: "From $900", image:"images/Amsterdam.jpg", info:"Step into the charming canals of Amsterdam, where each bridge tells a story and every street is a journey. Known for its picturesque waterways, historic architecture, and vibrant cultural scene, Amsterdam invites you to explore its unique blend of tradition and modernity. Cruise along the iconic canals, pedal through bike-friendly streets, and discover the treasures of world-class museums, including the Van Gogh Museum and Rijksmuseum. With its friendly atmosphere, diverse neighborhoods, and tulip-lined vistas, Amsterdam is a city that effortlessly captivates, offering a delightful experience for every traveler.", discount: "30%"},
    {id: 8, name: "Barcelona", price: "From $1000", image:"images/Barcelona.jpg", info:"Welcome to the dynamic city of Barcelona, where the spirit of Catalonia comes alive against a backdrop of modernist architecture, vibrant street life, and a rich cultural heritage. Explore the architectural wonders of Antoni Gaudí, including the iconic Sagrada Família and the whimsical Park Güell.", discount: "50%"},
    {id: 8, name: "England", price: "From $1400", image:"images/England.jpg", info:"Welcome to the timeless charm of England, a land where history unfolds amidst rolling green landscapes and bustling cityscapes. From the majestic towers of London to the poetic beauty of the Lake District, England is a tapestry of tradition and modernity. Immerse yourself in the cultural richness of Shakespearean theaters, explore ancient castles, and sip tea in quaint villages. With its iconic landmarks, vibrant pubs, and friendly locals, England invites you to discover its diverse heritage and create lasting memories in a setting that seamlessly blends the classic with the contemporary.", discount: "30%"}
    
    // Add more destinations as needed
  ];
  export default destinations;